logging:
  level:
    root: INFO
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
resilience4j:
  bulkhead:
    instances:
      bookStoreBulkhead:
        maxConcurrentCalls: 2
        maxWaitDuration: 0ms
  configs:
    default:
      registerHealthIndicator: true
  ratelimiter:
    instances:
      bookStoreLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 20s
        timeoutDuration: 0
  circuitbreaker:
    instances:
      bookstoreBackend:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 3
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 20s
        failure-rate-threshold: 10
        event-consumer-buffer-size: 10


resilience4j.retry:
  configs:
    default:
      enable-exponential-backoff: true
      exponential-backoff-multiplier: 4
      maxAttempts: 4
      waitDuration: 500
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - com.silva.bookstore.exception.BusinessException
  timelimiter:
    instances:
      bookStoreTimeout:
        cancelRunningFuture: true
        timeoutDuration: 600ms
server:
  port: 8082
spring:
  application:
    name: resilient-bookstore
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
