#spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false


spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  application:
    name: resilient-bookstore
resilience4j.ratelimiter:
    instances:
        bookStoreLimiter:
          registerHealthIndicator: true
          limitForPeriod: 2
          limitRefreshPeriod: 20s
          timeoutDuration: 0
server:
  port: 8082

