# This file contains two Kubernetes resources:
# 1. Deployment: Manages the Spring Boot application pods
#    - Runs a single replica of the application
#    - Mounts configuration from ConfigMap
#    - Configures health checks via actuator endpoints
#    - Uses local image 'healthcheck-example:latest'
# 
# 2. Service: Exposes the application to external traffic
#    - Type LoadBalancer makes it accessible from outside the cluster
#    - Maps port 80 to container port 8085
#    - Selects pods with label 'app: healthcheck-app'

apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcheck-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcheck-app
  template:
    metadata:
      labels:
        app: healthcheck-app
    spec:
      containers:
        - name: healthcheck-app
          image: healthcheck-example:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8085
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: healthcheck-service
spec:
  selector:
    app: healthcheck-app
  type: NodePort
  ports:
    - port: 8085
      targetPort: 8085
      nodePort: 30085
