
spring:
  application:
    name: Api Gateway Microservice
  cloud:
    gateway:
      default-filters:

      routes:
        - id: product
          uri: http://localhost:8082
          predicates:
            - Path=/product/**
        - id: client
          uri: http://localhost:8081
          predicates:
            -  Path=/clients/**
        - id: order
          uri: http://localhost:8083
          predicates:
            - Path=/order/**
  zipkin:
    base-url: http://localhost:9411/api/v2/spans
management:
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8090


