version: "3.8"
services:
  #docker run -d -p 9411:9411 openzipkin/zipkin
  zipkin:
    container_name: zipkin-ms
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      - spring-network
networks:
  spring-network:
    driver: bridge