server:
  port: 8082
spring:
  application:
    name: Product Microservice
  datasource:
    driverClassName: org.h2.Driver
    password: password
    url: jdbc:h2:mem:productdb
    username: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  zipkin:
    base-url: http://localhost:9411/api/v2/spans
management:
  tracing:
    sampling:
      probability: 1.0
